/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2000
    gain: 5.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: ture

    detect_color: 0
    binary_thres: 78

    # YOLO parser config file (relative to repo root or absolute). Used by Yolo11Node when launched.
    config_file: "autoaim/model/yolov11workconfig.json"

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 1.0
      sigma2_q_yaw: 50.0
      sigma2_q_r: 500.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-2

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

/vision_attacker:
  ros__parameters:
    trajectory:
      lag_time: 0.1
      air_k: 0.04
      yaw_fix: 0.5
      pitch_fix: -0.5
    fire_ctrl:
      car_attack_threshold: 85.0
      outpost_attack_threshold: 5.0
      threshold_fix: 0.0


  /yolo11_node:
    ros__parameters:
      config_file: "autoaim/model/yolov11workconfig.json"


# /rm_auto_record:
#   ros__parameters:
#     uri: "/ros_ws/"
#     topic_name:
#     - "/image_raw/compressed"
#     - "/camera_info"
#     - "/detector/armors"
#     topic_type:
#     - "sensor_msgs/msg/CompressedImage"
#     - "sensor_msgs/msg/CameraInfo"
#     - "auto_aim_interfaces/msg/Armors"